apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: nmost
spec:
  hosts:
  - "nmost.site"
  gateways:
  - grpc-gateway
  http:
  - name: "frontend-routes"
    match:
    - uri:
        prefix: "/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: frontend
        port:
          number: 80