apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
images:
- name: ghcr.io/impit-mpit/front-main
  newTag: c39a28b
- name: ghcr.io/impit-mpit/frontend-master
  newTag: latest
