/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { CategoryV1Category } from './categoryV1Category';

export interface CategoryV1GetCategoryFeedResponse {
  category?: CategoryV1Category[];
  total?: number;
}
