/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export * from './mediaServiceGetMediaFeedParams';
export * from './mediaV1CreateMediaRequest';
export * from './mediaV1GetMediaFeedResponse';
export * from './mediaV1Media';
export * from './mediaV1UpdateMediaRequest';
export * from './newsServiceGetNewsFeedParams';
export * from './newsV1CreateNewsRequest';
export * from './newsV1GetNewsFeedResponse';
export * from './newsV1News';
export * from './newsV1ShortNews';
export * from './newsV1UpdateNewsRequest';