/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { MediaV1Media } from './mediaV1Media';

export interface MediaV1GetMediaFeedResponse {
  media?: MediaV1Media[];
  total?: number;
}
