/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface MediaV1CreateMediaRequest {
  description?: string;
  thumbnailUrl?: string;
  title?: string;
  videoUrl?: string;
}
