/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface MediaV1ShortMedia {
  id?: string;
  shortDescription?: string;
  thumbnailUrl?: string;
  title?: string;
  videoUrl?: string;
}
