/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { MediaV1ShortMedia } from './mediaV1ShortMedia';

export interface MediaV1GetMediaFeedResponse {
  media?: MediaV1ShortMedia[];
  total?: number;
}
