/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface NewsV1CreateNewsRequest {
  body?: string;
  imageUrl?: string;
  shortBody?: string;
  title?: string;
}
