/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { NewsV1ShortNews } from './newsV1ShortNews';

export interface NewsV1GetNewsFeedResponse {
  news?: NewsV1ShortNews[];
  total?: number;
}
