/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { SpecialistV1Specialist } from './specialistV1Specialist';

export interface SpecialistV1GetSpecialistFeedResponse {
  Specialist?: SpecialistV1Specialist[];
  total?: number;
}
