/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface SpecialistV1Specialist {
  description?: string;
  fio?: string;
  id?: string;
  name?: string;
}
