/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { TagsV1Tags } from './tagsV1Tags';

export interface TagsV1GetTagsByCategoryResponse {
  tags?: TagsV1Tags[];
}
