/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  AiV1ChatResponse,
  MediaV1GetMediaFeedResponse,
  MediaV1Media,
  NewsV1GetNewsFeedResponse,
  NewsV1News
} from '../model'

export const getAIServiceChatResponseMock = (overrideResponse: Partial< AiV1ChatResponse > = {}): AiV1ChatResponse => ({message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), ...overrideResponse})

export const getMediaServiceGetMediaFeedResponseMock = (overrideResponse: Partial< MediaV1GetMediaFeedResponse > = {}): MediaV1GetMediaFeedResponse => ({media: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), shortDescription: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), thumbnailUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), videoUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined])})), undefined]), total: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), ...overrideResponse})

export const getMediaServiceGetMediaByIdResponseMock = (overrideResponse: Partial< MediaV1Media > = {}): MediaV1Media => ({description: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), thumbnailUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), videoUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), ...overrideResponse})

export const getNewsServiceGetNewsFeedResponseMock = (overrideResponse: Partial< NewsV1GetNewsFeedResponse > = {}): NewsV1GetNewsFeedResponse => ({news: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), shortBody: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), title: faker.helpers.arrayElement([faker.string.alpha(20), undefined])})), undefined]), total: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), ...overrideResponse})

export const getNewsServiceGetNewsByIdResponseMock = (overrideResponse: Partial< NewsV1News > = {}): NewsV1News => ({body: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), title: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), ...overrideResponse})


export const getAIServiceChatMockHandler = (overrideResponse?: AiV1ChatResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AiV1ChatResponse> | AiV1ChatResponse)) => {
  return http.post('*/v1/ai/chat', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getAIServiceChatResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getMediaServiceGetMediaFeedMockHandler = (overrideResponse?: MediaV1GetMediaFeedResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MediaV1GetMediaFeedResponse> | MediaV1GetMediaFeedResponse)) => {
  return http.get('*/v1/media', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getMediaServiceGetMediaFeedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getMediaServiceCreateMediaMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.post('*/v1/media', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getMediaServiceGetMediaByIdMockHandler = (overrideResponse?: MediaV1Media | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MediaV1Media> | MediaV1Media)) => {
  return http.get('*/v1/media/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getMediaServiceGetMediaByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getMediaServiceUpdateMediaMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.put('*/v1/media/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getMediaServiceDeleteMediaMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.delete('*/v1/media/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getNewsServiceGetNewsFeedMockHandler = (overrideResponse?: NewsV1GetNewsFeedResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NewsV1GetNewsFeedResponse> | NewsV1GetNewsFeedResponse)) => {
  return http.get('*/v1/news', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getNewsServiceGetNewsFeedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getNewsServiceCreateNewsMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.post('*/v1/news', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getNewsServiceGetNewsByIdMockHandler = (overrideResponse?: NewsV1News | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NewsV1News> | NewsV1News)) => {
  return http.get('*/v1/news/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getNewsServiceGetNewsByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getNewsServiceUpdateNewsMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.put('*/v1/news/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getNewsServiceDeleteNewsMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.delete('*/v1/news/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getMock = () => [
  getAIServiceChatMockHandler(),
  getMediaServiceGetMediaFeedMockHandler(),
  getMediaServiceCreateMediaMockHandler(),
  getMediaServiceGetMediaByIdMockHandler(),
  getMediaServiceUpdateMediaMockHandler(),
  getMediaServiceDeleteMediaMockHandler(),
  getNewsServiceGetNewsFeedMockHandler(),
  getNewsServiceCreateNewsMockHandler(),
  getNewsServiceGetNewsByIdMockHandler(),
  getNewsServiceUpdateNewsMockHandler(),
  getNewsServiceDeleteNewsMockHandler()
]
