/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VideosVideoidImport } from './routes/videos/$videoid'
import { Route as ArticleArticleidImport } from './routes/article/$articleid'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const VideosVideoidRoute = VideosVideoidImport.update({
  id: '/videos/$videoid',
  path: '/videos/$videoid',
  getParentRoute: () => rootRoute,
} as any)

const ArticleArticleidRoute = ArticleArticleidImport.update({
  id: '/article/$articleid',
  path: '/article/$articleid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/article/$articleid': {
      id: '/article/$articleid'
      path: '/article/$articleid'
      fullPath: '/article/$articleid'
      preLoaderRoute: typeof ArticleArticleidImport
      parentRoute: typeof rootRoute
    }
    '/videos/$videoid': {
      id: '/videos/$videoid'
      path: '/videos/$videoid'
      fullPath: '/videos/$videoid'
      preLoaderRoute: typeof VideosVideoidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/article/$articleid': typeof ArticleArticleidRoute
  '/videos/$videoid': typeof VideosVideoidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/article/$articleid': typeof ArticleArticleidRoute
  '/videos/$videoid': typeof VideosVideoidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/article/$articleid': typeof ArticleArticleidRoute
  '/videos/$videoid': typeof VideosVideoidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/article/$articleid' | '/videos/$videoid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/article/$articleid' | '/videos/$videoid'
  id: '__root__' | '/' | '/article/$articleid' | '/videos/$videoid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ArticleArticleidRoute: typeof ArticleArticleidRoute
  VideosVideoidRoute: typeof VideosVideoidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ArticleArticleidRoute: ArticleArticleidRoute,
  VideosVideoidRoute: VideosVideoidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/article/$articleid",
        "/videos/$videoid"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/article/$articleid": {
      "filePath": "article/$articleid.tsx"
    },
    "/videos/$videoid": {
      "filePath": "videos/$videoid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
